# Generated by Django 5.2.8 on 2025-11-25 12:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('download_url', models.URLField(blank=True)),
            ],
        ),
    ]
