# Generated by Django 5.2.8 on 2025-11-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together=set(),
        ),
    ]
